openapi: '3.0.2'
info:
  title: dynamodb-lambda-test-api
  version: '1.0'
  description: DynamoeDBとLambdaとAPI-Gatewayを連携して動作させるための勉強用のAPIです。
  content:

servers:
  - url: https://api.server.test/v1
# This file defines the API documentation for the application.
# The `paths` section is used to specify the available API endpoints,
# including their HTTP methods, parameters, request bodies, and responses.
paths:
  /items:
    get:
      responses:
        '200':
          description: OK
  /item/{id}:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: OK
      requestBody:
        description: authentication information to get token
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/item_name'
    delete:
      responses:
        '200':
          description: OK
  /auth:
    post:
      requestBody:
        description: authentication information to get token
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_info'
      responses:
        '200':
          description: OK
          content: {}
components:
  schemas:
    item_name:
      type: object
      properties:
        name:
          type: string
    auth_info:
      type: object
      properties:
        username:
            type: string
        password:
            type: string